jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      NODE_VERSION: 12.16.1
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
      NG_CLI_ANALYTICS: 'false'
      npm_config_cache: $(Pipeline.Workspace)/.npm

    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - task: NodeTool@0
        inputs:
          versionSpec: '12.16.1'
      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
          path: $(npm_config_cache)
        displayName: Cache npm
      - script: npm install
        displayName: 'TOOLS: npm install'
      # - script: sudo npm install -g npm
      #   displayName: 'TOOLS: update NPM'
      # - script: sudo chown -R vsts:docker /home/vsts/.npm/
      # displayName: 'BUGS-FIX: change /home/vsts/.npm/ permission'
      - script: sudo /etc/init.d/mysql stop
        displayName: 'TOOLS: stop MySQL'
      #----------------------------------------------------------------------
      # Tests
      #----------------------------------------------------------------------
      # - script: npm install
      # displayName: 'INSTALL: launch npm install'
      - script: |
          chmod +x gradlew
          ./gradlew checkstyleNohttp
          ./gradlew clean test integrationTest
        displayName: 'TESTS: backend'
      - script: ./gradlew npm_run_test-ci -PnodeInstall --no-daemon
        displayName: 'TESTS: frontend'
      - script: npm run chromatic
        displayName: 'UI review'
      - script: ./gradlew bootJar -Pprod -x test
        displayName: 'TESTS: packaging'
