orbs:
  slack: circleci/slack@3.4.2
version: 2.1
jobs:
    build:
        machine:
            image: circleci/classic:201808-01
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "package-lock.json" }}
                    - v1-dependencies-
            - run:
                name: Install OpenJDK 11
                command: |
                    sudo rm /var/lib/apt/lists/lock
                    sudo rm /var/cache/apt/archives/lock
                    sudo rm /var/lib/dpkg/lock
                    sudo apt install openjdk-11-jdk
                    echo 'export PATH="/usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH"' >> $BASH_ENV
            - run:
                name: Setup NVM
                command: |
                    echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
                    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            - run:
                name: Install Node 12.16.1
                command: |
                    nvm install 12.16.1
                    nvm alias default 12.16.1
            - run:
                name: Print Java Version
                command: 'java -version'
            - run:
                name: Print Node Version
                command: 'node -v'
            - run:
                name: Print NPM Version
                command: 'npm -v'
            - run:
                name: Install Node Modules
                command: 'npm install'

            - save_cache:
                paths:
                    - node
                    - node_modules
                    - ~/.gradle
                key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "package-lock.json" }}

            - run:
                name: Give Executable Power
                command: 'chmod +x gradlew'
            - run:
                name: Run Style Checks
                command: './gradlew checkstyleNohttp --no-daemon'
            - run:
                name: Clean and Verify
                command: './gradlew clean test integrationTest --no-daemon'
                when: always
            - store_test_results:
                path: ~/project/build/test-results/test/
            - store_test_results:
                path: ~/project/build/test-results/integrationTest/
            - run:
                name: Run Front End Tests
                command: npm run test-ci
                when: always
            - run:
                name: Run Chromatic
                command: npm run chromatic
                when: always
            - store_test_results:
                path: ~/project/build/test-results/test-ci/
            - run:
                name: Verify with Prod Profile
                command: './gradlew bootJar -Pprod -x test --no-daemon'
#            - run:
#                name: Deploy to Heroku
#                command: './gradlew deployHeroku --no-daemon'

            - slack/status:
                channel: rates-ci
                mentions: 'channel'
                include_job_number_field: true
                webhook: '${SLACK_WEBHOOK}'
