export const enum Qualification {
  HIGHER_NATIONAL_DIPLOMA = 'HIGHER_NATIONAL_DIPLOMA',

  HIGHER_NATIONAL_CERTIFICATE = 'HIGHER_NATIONAL_CERTIFICATE',

  A_LEVEL = 'A_LEVEL',

  BACHELORS_DEGREE = 'BACHELORS_DEGREE',

  MASTERS_DEGREE = 'MASTERS_DEGREE',

  PHD = 'PHD',
}
