enum STATES {
  ABIA = 'ABIA',
  ADAMAWA = 'ADAMAWA',
  AKWA_IBOM = 'AKWA_IBOM',
  ANAMBRA = 'ANAMBRA',
  BAUCHI = 'BAUCHI',
  BAYELSA = 'BAYELSA',
  BENUE = 'BENUE',
  BORNO = 'BORNO',
  CROSS_RIVER = 'CROSS_RIVER',
  DELTA = 'DELTA',
  EBONYI = 'EBONYI',
  ENUGU = 'ENUGU',
  EDO = 'EDO',
  EKITI = 'EKITI',
  FCT = 'FCT/ABUJA',
  GOMBE = 'GOMBE',
  IMO = 'IMO',
  JIGAWA = 'JIGAWA',
  KADUNA = 'KADUNA',
  KANO = 'KANO',
  KATSINA = 'KATSINA',
  KEBBI = 'KEBBI',
  KOGI = 'KOGI',
  KWARA = 'KWARA',
  LAGOS = 'LAGOS',
  NASARAWA = 'NASARAWA',
  NIGER = 'NIGER',
  OGUN = 'OGUN',
  ONDO = 'ONDO',
  OSUN = 'OSUN',
  OYO = 'OYO',
  PLATEAU = 'PLATEAU',
  RIVERS = 'RIVERS',
  SOKOTO = 'SOKOTO',
  TARABA = 'TARABA',
  YOBE = 'YOBE',
  ZAMFARA = 'ZAMFARA',
}

const stateI8NKey = (state: STATES) => `ratesApp.State.${state}`;

export const STATE_OPTIONS: { value: STATES; i8nKey: string }[] = Object.entries(STATES).map(([, value]) => ({
  value,
  i8nKey: stateI8NKey(value),
}));
